name: CI
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

env:
  GITHUB_SNAKE_OUTPUT_DIR: "dist"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-snake:
    name: GitHub Snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ${{ env.GITHUB_SNAKE_OUTPUT_DIR }}/github-snake.svg
      - name: Push auto-fixed files
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat ${{ env.GITHUB_SNAKE_OUTPUT_DIR }} | grep '[0-9]'); then \
            git add -A; \
            git commit -m "📊 Update github-snake by github-actions"; \
            git push origin ${GITHUB_REF_NAME}; \
          fi
