name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment'
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
      administration: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run opencode
        uses: anomalyco/opencode/github@github-v1.2.22
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/big-pickle
